version: '3'
services:
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: crilcq-mysql
        volumes:
            - crilcq_mysql:/var/lib/mysql
        networks:
            - crilcqnet
        environment:
            - TZ=Canada/Eastern
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: crilcq-proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - crilcqnet

    website:
        image: crilcq/website
        container_name: crilcq-website
        volumes:
            - crilcq_site_webroot:/var/www/html
        networks:
            - crilcqnet
        environment:
            - VIRTUAL_HOST=~^(www\.)?crilcq.org
        depends_on:
            - mysql
            - alfresco

    orion:
        image: httpd:2.4
        container_name: crilcq-orion
        volumes:
            - crilcq_orion:/usr/local/apache2/htdocs
        networks:
            - crilcqnet
        environment:
            - VIRTUAL_HOST=orion.crilcq.org
        depends_on:
            - alfresco

    alfresco:
        image: crilcq/alfresco
        container_name: crilcq-alfresco
        volumes:
            - crilcq_alf_data:/alf_data
            - crilcq_tomcat:/var/lib/tomcat7
        networks:
            - crilcqnet
        environment:
            - VIRTUAL_HOST=alfresco.crilcq.org
            - VIRTUAL_PORT=8080
        depends_on:
            - mysql

volumes:
    crilcq_mysql:
    crilcq_site_webroot:
    crilcq_orion:
    crilcq_alf_data:
    crilcq_tomcat:

networks:
    crilcqnet:
