<?php
return array(
	'BE' => array(
		'debug' => FALSE,
		'explicitADmode' => 'explicitAllow',
		'installToolPassword' => '$P$CXQzi/aq1CuO9.IxBKHY1B1SFfswPl0',
		'loginSecurityLevel' => 'rsa',
		'maxFileSize' => '65536',
		'sessionTimeout' => '6400',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'typo3',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'crilcq-mysql',
		'password' => 'GNpI4uz22dc3VX6VC',
		'port' => 3306,
		'socket' => '',
		'username' => 'typo3',
	),
	'EXT' => array(
		'extConf' => array(
			'cal' => 'a:23:{s:13:"noTabDividers";s:1:"0";s:21:"hideLocationTextfield";s:1:"0";s:22:"hideOrganizerTextfield";s:1:"1";s:20:"useLocationStructure";s:15:"tx_cal_location";s:21:"useOrganizerStructure";s:16:"tx_cal_organizer";s:11:"todoSubtype";s:5:"event";s:16:"categoryTVHeight";s:3:"280";s:11:"treeOrderBy";s:5:"title";s:9:"showTimes";s:1:"1";s:9:"useTeaser";s:1:"0";s:17:"useRecordSelector";s:1:"0";s:20:"useNewRecurringModel";s:1:"1";s:20:"hideDeviationRecords";s:1:"1";s:15:"categoryService";s:12:"sys_category";s:15:"recurrenceStart";s:8:"20140101";s:13:"recurrenceEnd";s:8:"20201231";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:8:"lifetime";s:13:"cacheLifetime";s:4:"3600";s:13:"cachingEngine";s:8:"internal";s:30:"enableRealURLAutoConfiguration";s:1:"1";s:10:"newRecurUI";s:1:"1";s:13:"updateMessage";s:1:"0";}',
			'crilcq' => 'a:0:{}',
			'crilcq_fful' => 'a:0:{}',
			'cuser' => 'a:0:{}',
			'danp_realurlconfigurator' => 'a:1:{s:18:"includeRealUrlConf";s:1:"1";}',
			'datamints_feuser' => 'a:3:{s:10:"enableIrre";s:1:"1";s:13:"encryptionKey";s:32:"b98OQ8c5hhmH1dwVyk3po8K8I9kQ0KHm";s:16:"enableSalesforce";s:1:"0";}',
			'div2007' => 'a:0:{}',
			'dynamicgooglesitemap' => 'a:4:{s:12:"ignoreParams";s:8:"L, cHash";s:14:"ignorePageType";s:2:"98";s:7:"sorting";s:3:"uid";s:15:"respectNoSearch";s:1:"1";}',
			'euser' => 'a:0:{}',
			'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
			'femanager' => 'a:2:{s:13:"disableModule";s:1:"0";s:10:"disableLog";s:1:"0";}',
			'fluidwidget' => 'a:0:{}',
			'html5videoplayer' => 'a:3:{s:20:"generalStorageFolder";s:1:"0";s:14:"generalMinWith";s:3:"200";s:16:"generalMinHeight";s:3:"150";}',
			'jb_realurl_regeneration' => 'a:5:{s:12:"TSFE_page_id";s:1:"1";s:8:"CLI_HOST";s:10:"crilcq.org";s:16:"tablesToGenerate";s:13:"pages,tt_news";s:15:"deleteUniqAlias";s:1:"0";s:21:"deleteUniqAliasTables";s:7:"tt_news";}',
			'kickstarter' => 'a:0:{}',
			'listeclas' => 'a:0:{}',
			'listeclasse' => 'a:0:{}',
			'listetable' => 'a:0:{}',
			'listfeusers' => 'a:0:{}',
			'listusers' => 'a:0:{}',
			'me_google_calendar' => 'a:0:{}',
			'mediaoembed' => 'a:0:{}',
			'monext' => 'a:0:{}',
			'mp_personsearch' => 'a:0:{}',
			'news' => 'a:17:{s:29:"removeListActionFromFlexforms";s:1:"2";s:20:"pageModuleFieldsNews";s:317:"LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_advanced=title,datetime,teaser,categories;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_complex=title,datetime,teaser,categories,archive;";s:24:"pageModuleFieldsCategory";s:28:"title,description,categories";s:11:"archiveDate";s:8:"datetime";s:13:"prependAtCopy";s:1:"1";s:6:"tagPid";s:1:"1";s:25:"showMediaDescriptionField";s:1:"0";s:12:"rteForTeaser";s:1:"0";s:22:"contentElementRelation";s:1:"0";s:13:"manualSorting";s:1:"0";s:19:"categoryRestriction";s:4:"none";s:34:"categoryBeGroupTceFormsRestriction";s:1:"0";s:6:"useFal";s:1:"1";s:12:"showImporter";s:1:"0";s:18:"storageUidImporter";s:1:"1";s:22:"resourceFolderImporter";s:12:"/news_import";s:24:"showAdministrationModule";s:1:"1";}',
			'nn_address' => 'a:2:{s:8:"flexForm";s:45:"EXT:nn_address/Configuration/FlexForms/Model/";s:14:"flexFormPlugin";s:39:"EXT:nn_address/Configuration/FlexForms/";}',
			'party' => 'a:0:{}',
			'pb_filelist' => 'a:1:{s:18:"denyFileExtensions";s:9:"php, html";}',
			'phpmyadmin' => 'a:5:{s:12:"hideOtherDBs";s:1:"1";s:9:"uploadDir";s:21:"uploads/tx_phpmyadmin";s:10:"allowedIps";s:0:"";s:12:"useDevIpMask";s:1:"0";s:10:"ajaxEnable";s:1:"1";}',
			'realurl' => 'a:6:{s:10:"configFile";s:11:"realurl.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'roq_newsevent' => 'a:0:{}',
			'rounded_corners' => 'a:0:{}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
			'rtehtmlarea' => 'a:8:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"forceCommandMode";s:1:"0";}',
			'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
			'scheduler' => 'a:5:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";s:30:"listShowTaskDescriptionAsHover";s:1:"1";}',
			'sr_feuser_register' => 'a:4:{s:12:"uploadFolder";s:27:"uploads/tx_srfeuserregister";s:10:"imageTypes";s:30:"png, jpg, jpeg, gif, tif, tiff";s:12:"imageMaxSize";s:3:"500";s:16:"enableDirectMail";s:1:"0";}',
			'static_info_tables' => 'a:2:{s:13:"enableManager";s:1:"0";s:5:"dummy";s:1:"0";}',
			'static_info_tables_fr' => 'a:1:{s:5:"dummy";s:1:"0";}',
			'tt_address' => 'a:4:{s:21:"backwardsCompatFormat";s:9:"%1$s %3$s";s:24:"storeBackwardsCompatName";s:1:"1";s:17:"readOnlyNameField";s:1:"1";s:24:"disableCombinedNameField";s:1:"0";}',
			'vhs' => 'a:0:{}',
			'we_google_analytics' => 'a:0:{}',
			'wec_map' => 'a:1:{s:7:"apiKey.";a:1:{s:6:"google";a:1:{s:14:"www.crilcq.org";N;}}}',
			'ws_imageeffects' => 'a:0:{}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'fr',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'activateContentAdapter' => FALSE,
		'debug' => FALSE,
		'loginSecurityLevel' => 'rsa',
	),
	'GFX' => array(
		'colorspace' => 'RGB',
		'im' => 1,
		'im_mask_temp_ext_gif' => 1,
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '/usr/bin/',
		'im_v5effects' => -1,
		'im_version_5' => 'gm',
		'image_processing' => 1,
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\Updates\FilemountUpdateWizard' => 1,
			'TYPO3\CMS\Install\Updates\ProcessedFileChecksumUpdate' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
			'TYPO3\CMS\Install\Updates\TruncateSysFileProcessedFileTable' => 1,
		),
	),
	'SYS' => array(
		'UTF8filesystem' => '1',
		'caching' => array(
			'cacheConfigurations' => array(
				'extbase_object' => array(
					'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
			),
		),
		'clearCacheSystem' => FALSE,
		'compat_version' => '6.2',
		'devIPmask' => '',
		'displayErrors' => 0,
		'enableDeprecationLog' => FALSE,
		'encryptionKey' => 'ae60c2d9686e709795bddb0c8ceccc977828d1a577fecc8a5b1b75202078de90e5136c04e13df8038329b003b9afe6ec',
		'isInitialInstallationInProgress' => FALSE,
		'phpTimeZone' => 'America/Montreal',
		'serverTimeZone' => '-5',
		'sitename' => 'CRILCQ',
		'sqlDebug' => 0,
		'systemLocale' => 'fr_CA.utf8',
		'systemLogLevel' => 2,
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
	),
);
?>
